PROJECT_NAME=digodoc-indexer
DATABASE:=digodoc
API_HOST:=http://localhost:8080    # external address of your API server
API_PORT:=8080                     # internal port of your API server
RLS_DIR:=www                       # release folder (/var/www/...)
CONTACT_EMAIL:=                    # email address displayed on API doc
VERSION:=1.0                       # API version displayed on API doc
DIGODOC_DIR:=~/DIGODOC/digodoc/_digodoc/html/
